name: PlugMan
main: com.rylinaux.plugman.PlugMan
version: 2.0.5
description: Plugin manager for Bukkit servers
author: rylinaux
commands:
  plugman:
    description: Manage plugins.
    usage: /plugman [help|dump]
           /plugman list [-v]
           /plugman [enable|disable|restart] [plugin|all]
           /plugman [info|usage|load|reload|unload|check] [plugin]
permissions:
  plugman.admin:
    description: Allows use of all PlugMan commands.
    default: op
    children:
      plugman.update: true
      plugman.help: true
      plugman.help: true
      plugman.list: true
      plugman.dump: true
      plugman.info: true
      plugman.usage: true
      plugman.enable: true
      plugman.enable.all: true
      plugman.disable: true
      plugman.disable.all: true
      plugman.restart: true
      plugman.restart.all: true
      plugman.load: true
      plugman.reload: true
      plugman.unload: true
      plugman.check: true
  plugman.update:
    description: Allows the player to see the update alerts.
    default: op
  plugman.help:
    description: Allows use of the help command.
    default: op
  plugman.list:
    description: Allows use of the list command.
    default: op
  plugman.dump:
    description: Allows use of the dump command.
    default: op
  plugman.info:
    description: Allows use of the info command.
    default: op
  plugman.usage:
    description: Allows use of the usage command.
    default: op
  plugman.enable:
    description: Allows use of the enable command.
    default: op
  plugman.enable.all:
    description: Allows use of the enable all command.
    default: op
  plugman.disable:
    description: Allows use of the disable command.
    default: op
  plugman.disable.all:
    description: Allows use of the disable all command.
    default: op
  plugman.restart:
    description: Allows use of the restart command.
    default: op
  plugman.restart.all:
    description: Allows use of the restart all command.
    default: op
  plugman.load:
    description: Allows use of the load command.
    default: op
  plugman.reload:
    description: Allows use of the reload command.
    default: op
  plugman.unload:
    description: Allows use of the unload command.
    default: op
  plugman.check:
    description: Allows use of the check command.
    default: op